/**
 * Cat Fostering API
 * Cat Fostering OpenAPI specifications
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fostering } from './fostering';
import { User } from './user';

export interface CatProfile {
  id: string;
  name: string;
  age: number;
  description: string;
  photosUrls: Array<string>;
  owner: User;
  fosterings?: Array<Fostering>;
}
