/**
 * Cat Fostering API
 * Cat Fostering OpenAPI specifications
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatProfile } from './catProfile';
import { User } from './user';

export interface Fostering {
  id: string;
  startDate: string;
  endDate: string;
  status: Fostering.StatusEnum;
  catProfile: CatProfile;
  participant: User;
}
export namespace Fostering {
  export type StatusEnum = 'PENDING' | 'APPROVED' | 'REJECTED';
  export const StatusEnum = {
    Pending: 'PENDING' as StatusEnum,
    Approved: 'APPROVED' as StatusEnum,
    Rejected: 'REJECTED' as StatusEnum,
  };
}
