/**
 * Cat Fostering API
 * Cat Fostering OpenAPI specifications
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OryIdentityDtoMetadataPublic } from './oryIdentityDtoMetadataPublic';
import { OryIdentityTraitDto } from './oryIdentityTraitDto';

export interface OryIdentityDto {
  id: string;
  schema_id: string;
  schema_url: string;
  traits: OryIdentityTraitDto;
  state?: OryIdentityDto.StateEnum;
  recovery_addresses?: Array<object>;
  verifiable_addresses?: Array<object>;
  credentials?: object;
  metadata_public: OryIdentityDtoMetadataPublic;
  metadata_admin?: object;
  created_at?: string;
  updated_at?: string;
  state_changed_at?: string;
}
export namespace OryIdentityDto {
  export type StateEnum = 'active' | 'inactive';
  export const StateEnum = {
    Active: 'active' as StateEnum,
    Inactive: 'inactive' as StateEnum,
  };
}
