/**
 * Cat Fostering API
 * Cat Fostering OpenAPI specifications
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatProfile } from './catProfile';
import { Fostering } from './fostering';

export interface User {
  id: string;
  name: string;
  email: string;
  catProfiles?: Array<CatProfile>;
  fosteringActivities?: Array<Fostering>;
}
