name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
  POSTGRES_URL: postgres://dbuser:secret@localhost:5432
  POSTGRES_DB: cat_fostering_api_e2e

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx affected -t lint test build

      #  can't use --wait --wait-timeout N options since Keto and Kratos migrate containers will exit before the Keto and Kratos services are ready
      - run: npx @dotenvx/dotenvx run -- docker compose --profile ci -p cat-fostering up -d

      - run: sleep 15

      - run: npx nx run cat-fostering-api:serve:ci &
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - run: sleep 10

      - run: npx nx affected -t e2e
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      # to enable DTE for split e2e tests, use the following command instead and update stop-agents-after accordingly
      # - run: npx nx affected -t e2e-ci
